$(document).ready(function(){


  $("#determinate-loader").css("width","100%");

  ListOfPhysicsConstants = JSON.parse($("#main-screen").attr("lopc"));

  setTimeout(function(){
    //we need to intialize user data if there is any to init
    InitEditorWithEditorData();
    $("#loading-screen").animate({
      opacity: 0.0
    },500,function(){
      $(this).css("display","none");
    });
  },2100);

  window.onbeforeunload = function (e) {
    if(SaveEditorData){
      SaveEditorDataToLocalStorage();
    }else{
      localStorage.removeItem("editor-data");
    }
    
  };


  $(".static-physics-equation").each(function(i){
    MQ.StaticMath($(this).get(0)).latex($(this).attr("latex"));
  });

  $(".keyboard-latex").each(function(i){
    MQ.StaticMath($(this).get(0),{});
  });

  //setting the mathfields for the warning message box
  MessageBoxMathFields.question.m1 = MQ.StaticMath($("#question-box-static-mathfield")[0]);
  MessageBoxMathFields.warning.m1 = MQ.StaticMath($("#warning-box-undefined-vars")[0]);

  $('.tabs').tabs();
  $('.dropdown-trigger').dropdown();

  $("#modal-physics-equation-more-information, #modal-user-guide, #modal-create-custom-unit").modal();
  $("#modal_import_variable_definition").modal({
    onOpenStart: function(){
      $("#btn-update-imported-variables").addClass("disabled");
    },
  });
  $("#modal-create-custom-unit").modal({
    onOpenEnd: function(){
      // copying whatever the user wrote in the units dropdown into the custom si units modal
      $("#input-custom-unit").val($("#input-user-units-search").val());
      // focusing on the input so the user can get to editing and creating the custom unit
      $("#input-custom-unit").focus();
      ParseAndRenderCustomUnit();
    },
  });

  $('.collapsible').collapsible();
  $("#physics_equations .collapsible").collapsible({
    onOpenEnd: function(){
      //there are some equations that are too long to fit into the space alotted so I am finding them and making their font size a bit smaller so they don't overlap into other equations
      $("#physics_equations .collapsible li.active .static-physics-equation").each(function(){
        //console.log($(this).width(), $(this).parent(".col").width());
        if($(this).width() > $(this).parent(".col").width()){
          $(this).css("font-size","13px");
        }
      });
    }
  });

  $('.tooltipped').tooltip();
  $('#side-nav-editor-log').sidenav({
    edge: 'right',
    preventScrolling: false,
  });

  $("#equations_container").height($(window).height() - 64);
  $("#physics_equations").height($(window).height() - $("#physics_equations").offset().top - 70);
  $("#physics_constants").height($(window).height() - $("#physics_constants").offset().top - 100);
  $("#my_variables").height($(window).height() - $("#my_variables").offset().top - 100);

  $("#my_variables .collection-item").hover(function(){
    $("#my_variables .collection-item").removeClass('active');
    $(this).addClass('active');
  },function(){
    $(this).removeClass('active');
  });

  $(".physics-constant-checkbox-span").each(function(){
    $(this).click(function(){
      CheckIfPhysicsConstantCheckboxIsDisabled($(this));
    });
  });

  $(".physics-constant-checkbox-input").each(function(i){
    $(this).change(function(){
      TogglePhysicsConstant($(this), i);
    });
  });

  AutoGeneratedUnitData = GenerateAutoCompleteData();

  $(document).mousedown(function(){
    MOUSEDOWN = true;
  }).mouseup(function(){
    MOUSEDOWN = false;
  });


  $(".my_math_field").click(function(){
    FocusedMathFieldId = $(this).attr("id");
  });

  $("#math_field_editor_container").css("height",`${window.innerHeight - $("#math_field_editor_container").offset().top}px`);
  RecalculateHeightOfLineEmptySpace();
  $("#my_variables-collection-container").css("height",`${window.innerHeight - $("#my_variables-collection-container")[0].getBoundingClientRect().top}px`);

  $("#editor-log-container .collapsible .collapsible-body.information-container").css("max-height",`${window.innerHeight - $("#editor-log-container .collapsible.log-container").height()}px`);

  //when user is searching for units in the units dropdown
  $("#input-user-units-search").on("input",function(){
    RenderSIUnitsSearch();
  });

  $("#input-custom-unit").on("input",function(){
    ParseAndRenderCustomUnit();
  });

  $("#main-screen").click(function(e){
    MainScreenClicked(e);
  });

  $(".variable-checkbox").change(function(){
    $("#btn-update-imported-variables").removeClass("disabled");
  });


  //adding event listener to physics equation headers so  that when they are mouseovered or mouse we can show or hide the informational videos accordingly
  $(".static-physics-equation-header").mouseout(function(e){
    let id = $(this).attr("infoId");
    if($(e.relatedTarget).attr("id") != id && $(`#${id}`).find(e.relatedTarget).length == 0){
      HideInfoPopup(id);
    }
  }).mouseover(function(){
    if($(this).attr("info") != undefined){
      let id = $(this).attr("infoId");
      if($(`#${id}.more-information-videos-container`).length == 0){
        //this means that more information Popup hasn't been created so we will create it
        CreateInfoPopup(id, JSON.parse($(this).attr("info")));
      }
      DisplayInfoPopup(id, $(this).children('span')[0].getBoundingClientRect());
    }
    
  });

  $(".static-physics-equation-header > span").mouseout(function(e){
    //if we mouseout into the spans parent we don't care but if we mouse out into something else then we do care
    if(!$(e.relatedTarget).hasClass("static-physics-equation-header")){
      HideInfoPopup($(this).parent(".static-physics-equation-header").attr("infoId"));
    }
  }).mouseover(function(){
    let el = $(this).parent(".static-physics-equation-header");
    if(el.attr("info") != undefined){
      let id = el.attr("infoId");
      if($(`#${id}.more-information-videos-container`).length == 0){
        //this means that more information Popup hasn't been created so we will create it
        CreateInfoPopup(id, JSON.parse(el.attr("info")));
      }
      DisplayInfoPopup(id, $(this).get(0).getBoundingClientRect());
    }
  });

});
